title: Hugo Valdivia
logo: /img/photo.png
description: > 
  I am a recent graduate from Stanford's Computer Science Master's program looking for opportunities in software engineering and machine learning. 
  <br><br>
  <a href="https://www.linkedin.com/in/hugo-valdivia">View My LinkedIn Profile</a> 


theme: jekyll-theme-minimal
